apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: org-runnerdeploy
spec:
  replicas: 2
  template:
    spec:
      organization: github-actions-repo
      repository: github-actions-repo/scratchpad