name: Node.js CI - Reusable Composite Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Build Node
      uses: ./.github/actions/build-node