name: Environment Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - ci/*

jobs:
  live-job:
    environment: live
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - run: echo "${{ vars.ENV_VAL }}" >> $GITHUB_STEP_SUMMARY

  dev-job:
    environment: development
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - run: echo "${{ vars.ENV_VAL }}"  >> $GITHUB_STEP_SUMMARY