name: Test Deployment

on:
  pull_request:

jobs:
  dev-job:
    environment: development
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - run: echo "${{ vars.ENV_VAL }}"  >> $GITHUB_STEP_SUMMARY