name: Node.js in a docker container

on:
  workflow_dispatch:

jobs:
  node_job:
    runs-on: ${{ vars.JOBS_RUNNER }}
    container:
      image: node:21-alpine3.18
    #   credentials:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
    #   env:
    #     NODE_ENV: production
    #   ports:
    #     - 8080:8080
    #   volumes:
    #     - /path/in/runner:/path/in/container
    #   options: --cpus 1
    steps:
      - name: Run a command
        run: node --version