name: Node.js CI - Reusable Composite Workflow

on:
    workflow_dispatch:
    push:

jobs:
  ci:
    name: Run build process
    uses: github-actions-repo/scratchpad/.github/workflows/build-node-composite.yml@master