name: Node.js CI - Reusable Composite Workflow

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    name: Run build process
    uses: github-actions-repo/scratchpad/.github/actions/reusable-workflow/build-with-cache-composite.yml@master